---
# file: webservers.yml
- hosts: webservers
  remote_user: rkarna
  sudo: yes
  roles:
    - common
    - webtier
  tasks:
    - service: name=nginx state=started
      sudo: yes
-nginx_sites:
  default:
    - listen 80
    - server_name jenkins.sequenceiq.com
    - location / {
       proxy_pass http://jenkins;
       proxy_redirect off;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Host $server_name;
      }
-nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP $remote_addr
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  upstream:
    - upstream jenkins { server 127.0.0.1:8080 weight=10; }

